### ISSUE TITLE
Prediction of result based on FP1/2/3

### ISSUE THREAD

**Issue by walteij** [Draichi/formula1-AI#1]
Not really an issue, but I was wondering if it would be able to predict the race results using this model.
No I'm not a betting man, but we do have an F1 scorito group at work that I would love to win ;)

**Comment by Draichi** [comment]
hi @walteij I only seeing this rn, I didn't receive a notification.

you would need to train the model in a different way if you want to predict the race result only based on FP1/2/3 results. You would need to use historical FP1/2/3 data as features and the quali or race result as the label. After training, you would input the FP data you have to the model and it would output a prediction.

but because a lot of things can happen in a race, this type of prediction would have really low accuracy.

it works best predicting more direct outputs like the next lap time or thinks like this

I hope this helps
